// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v50/github"

	mock "github.com/stretchr/testify/mock"
)

// MockPullRequestsInterface is an autogenerated mock type for the pullRequestsInterface type
type MockPullRequestsInterface struct {
	mock.Mock
}

type MockPullRequestsInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullRequestsInterface) EXPECT() *MockPullRequestsInterface_Expecter {
	return &MockPullRequestsInterface_Expecter{mock: &_m.Mock}
}

// ListFiles provides a mock function with given fields: ctx, owner, repo, number, opts
func (_m *MockPullRequestsInterface) ListFiles(ctx context.Context, owner string, repo string, number int, opts *github.ListOptions) ([]*github.CommitFile, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, number, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []*github.CommitFile
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *github.ListOptions) ([]*github.CommitFile, *github.Response, error)); ok {
		return rf(ctx, owner, repo, number, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *github.ListOptions) []*github.CommitFile); ok {
		r0 = rf(ctx, owner, repo, number, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.CommitFile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, *github.ListOptions) *github.Response); ok {
		r1 = rf(ctx, owner, repo, number, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, *github.ListOptions) error); ok {
		r2 = rf(ctx, owner, repo, number, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPullRequestsInterface_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockPullRequestsInterface_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - opts *github.ListOptions
func (_e *MockPullRequestsInterface_Expecter) ListFiles(ctx interface{}, owner interface{}, repo interface{}, number interface{}, opts interface{}) *MockPullRequestsInterface_ListFiles_Call {
	return &MockPullRequestsInterface_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, owner, repo, number, opts)}
}

func (_c *MockPullRequestsInterface_ListFiles_Call) Run(run func(ctx context.Context, owner string, repo string, number int, opts *github.ListOptions)) *MockPullRequestsInterface_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(*github.ListOptions))
	})
	return _c
}

func (_c *MockPullRequestsInterface_ListFiles_Call) Return(_a0 []*github.CommitFile, _a1 *github.Response, _a2 error) *MockPullRequestsInterface_ListFiles_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPullRequestsInterface_ListFiles_Call) RunAndReturn(run func(context.Context, string, string, int, *github.ListOptions) ([]*github.CommitFile, *github.Response, error)) *MockPullRequestsInterface_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPullRequestsInterface creates a new instance of MockPullRequestsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullRequestsInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullRequestsInterface {
	mock := &MockPullRequestsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
