// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v50/github"

	mock "github.com/stretchr/testify/mock"
)

// MockIssuesInterface is an autogenerated mock type for the issuesInterface type
type MockIssuesInterface struct {
	mock.Mock
}

type MockIssuesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssuesInterface) EXPECT() *MockIssuesInterface_Expecter {
	return &MockIssuesInterface_Expecter{mock: &_m.Mock}
}

// AddLabelsToIssue provides a mock function with given fields: ctx, owner, repo, number, labels
func (_m *MockIssuesInterface) AddLabelsToIssue(ctx context.Context, owner string, repo string, number int, labels []string) ([]*github.Label, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, number, labels)

	if len(ret) == 0 {
		panic("no return value specified for AddLabelsToIssue")
	}

	var r0 []*github.Label
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, []string) ([]*github.Label, *github.Response, error)); ok {
		return rf(ctx, owner, repo, number, labels)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, []string) []*github.Label); ok {
		r0 = rf(ctx, owner, repo, number, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Label)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, []string) *github.Response); ok {
		r1 = rf(ctx, owner, repo, number, labels)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, []string) error); ok {
		r2 = rf(ctx, owner, repo, number, labels)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIssuesInterface_AddLabelsToIssue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLabelsToIssue'
type MockIssuesInterface_AddLabelsToIssue_Call struct {
	*mock.Call
}

// AddLabelsToIssue is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - labels []string
func (_e *MockIssuesInterface_Expecter) AddLabelsToIssue(ctx interface{}, owner interface{}, repo interface{}, number interface{}, labels interface{}) *MockIssuesInterface_AddLabelsToIssue_Call {
	return &MockIssuesInterface_AddLabelsToIssue_Call{Call: _e.mock.On("AddLabelsToIssue", ctx, owner, repo, number, labels)}
}

func (_c *MockIssuesInterface_AddLabelsToIssue_Call) Run(run func(ctx context.Context, owner string, repo string, number int, labels []string)) *MockIssuesInterface_AddLabelsToIssue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].([]string))
	})
	return _c
}

func (_c *MockIssuesInterface_AddLabelsToIssue_Call) Return(_a0 []*github.Label, _a1 *github.Response, _a2 error) *MockIssuesInterface_AddLabelsToIssue_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIssuesInterface_AddLabelsToIssue_Call) RunAndReturn(run func(context.Context, string, string, int, []string) ([]*github.Label, *github.Response, error)) *MockIssuesInterface_AddLabelsToIssue_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function with given fields: ctx, owner, repo, number, comment
func (_m *MockIssuesInterface) CreateComment(ctx context.Context, owner string, repo string, number int, comment *github.IssueComment) (*github.IssueComment, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, number, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 *github.IssueComment
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *github.IssueComment) (*github.IssueComment, *github.Response, error)); ok {
		return rf(ctx, owner, repo, number, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *github.IssueComment) *github.IssueComment); ok {
		r0 = rf(ctx, owner, repo, number, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.IssueComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, *github.IssueComment) *github.Response); ok {
		r1 = rf(ctx, owner, repo, number, comment)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, *github.IssueComment) error); ok {
		r2 = rf(ctx, owner, repo, number, comment)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIssuesInterface_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockIssuesInterface_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - comment *github.IssueComment
func (_e *MockIssuesInterface_Expecter) CreateComment(ctx interface{}, owner interface{}, repo interface{}, number interface{}, comment interface{}) *MockIssuesInterface_CreateComment_Call {
	return &MockIssuesInterface_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, owner, repo, number, comment)}
}

func (_c *MockIssuesInterface_CreateComment_Call) Run(run func(ctx context.Context, owner string, repo string, number int, comment *github.IssueComment)) *MockIssuesInterface_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(*github.IssueComment))
	})
	return _c
}

func (_c *MockIssuesInterface_CreateComment_Call) Return(_a0 *github.IssueComment, _a1 *github.Response, _a2 error) *MockIssuesInterface_CreateComment_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIssuesInterface_CreateComment_Call) RunAndReturn(run func(context.Context, string, string, int, *github.IssueComment) (*github.IssueComment, *github.Response, error)) *MockIssuesInterface_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// EditComment provides a mock function with given fields: ctx, owner, repo, id, comment
func (_m *MockIssuesInterface) EditComment(ctx context.Context, owner string, repo string, id int64, comment *github.IssueComment) (*github.IssueComment, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, id, comment)

	if len(ret) == 0 {
		panic("no return value specified for EditComment")
	}

	var r0 *github.IssueComment
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.IssueComment) (*github.IssueComment, *github.Response, error)); ok {
		return rf(ctx, owner, repo, id, comment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, *github.IssueComment) *github.IssueComment); ok {
		r0 = rf(ctx, owner, repo, id, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.IssueComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, *github.IssueComment) *github.Response); ok {
		r1 = rf(ctx, owner, repo, id, comment)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int64, *github.IssueComment) error); ok {
		r2 = rf(ctx, owner, repo, id, comment)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIssuesInterface_EditComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditComment'
type MockIssuesInterface_EditComment_Call struct {
	*mock.Call
}

// EditComment is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - id int64
//   - comment *github.IssueComment
func (_e *MockIssuesInterface_Expecter) EditComment(ctx interface{}, owner interface{}, repo interface{}, id interface{}, comment interface{}) *MockIssuesInterface_EditComment_Call {
	return &MockIssuesInterface_EditComment_Call{Call: _e.mock.On("EditComment", ctx, owner, repo, id, comment)}
}

func (_c *MockIssuesInterface_EditComment_Call) Run(run func(ctx context.Context, owner string, repo string, id int64, comment *github.IssueComment)) *MockIssuesInterface_EditComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].(*github.IssueComment))
	})
	return _c
}

func (_c *MockIssuesInterface_EditComment_Call) Return(_a0 *github.IssueComment, _a1 *github.Response, _a2 error) *MockIssuesInterface_EditComment_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIssuesInterface_EditComment_Call) RunAndReturn(run func(context.Context, string, string, int64, *github.IssueComment) (*github.IssueComment, *github.Response, error)) *MockIssuesInterface_EditComment_Call {
	_c.Call.Return(run)
	return _c
}

// ListComments provides a mock function with given fields: ctx, owner, repo, number, opts
func (_m *MockIssuesInterface) ListComments(ctx context.Context, owner string, repo string, number int, opts *github.IssueListCommentsOptions) ([]*github.IssueComment, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, number, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListComments")
	}

	var r0 []*github.IssueComment
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *github.IssueListCommentsOptions) ([]*github.IssueComment, *github.Response, error)); ok {
		return rf(ctx, owner, repo, number, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, *github.IssueListCommentsOptions) []*github.IssueComment); ok {
		r0 = rf(ctx, owner, repo, number, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.IssueComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, *github.IssueListCommentsOptions) *github.Response); ok {
		r1 = rf(ctx, owner, repo, number, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, *github.IssueListCommentsOptions) error); ok {
		r2 = rf(ctx, owner, repo, number, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIssuesInterface_ListComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComments'
type MockIssuesInterface_ListComments_Call struct {
	*mock.Call
}

// ListComments is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - opts *github.IssueListCommentsOptions
func (_e *MockIssuesInterface_Expecter) ListComments(ctx interface{}, owner interface{}, repo interface{}, number interface{}, opts interface{}) *MockIssuesInterface_ListComments_Call {
	return &MockIssuesInterface_ListComments_Call{Call: _e.mock.On("ListComments", ctx, owner, repo, number, opts)}
}

func (_c *MockIssuesInterface_ListComments_Call) Run(run func(ctx context.Context, owner string, repo string, number int, opts *github.IssueListCommentsOptions)) *MockIssuesInterface_ListComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(*github.IssueListCommentsOptions))
	})
	return _c
}

func (_c *MockIssuesInterface_ListComments_Call) Return(_a0 []*github.IssueComment, _a1 *github.Response, _a2 error) *MockIssuesInterface_ListComments_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIssuesInterface_ListComments_Call) RunAndReturn(run func(context.Context, string, string, int, *github.IssueListCommentsOptions) ([]*github.IssueComment, *github.Response, error)) *MockIssuesInterface_ListComments_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssuesInterface creates a new instance of MockIssuesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuesInterface {
	mock := &MockIssuesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
