// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v50/github"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockRepositoriesInterface is an autogenerated mock type for the repositoriesInterface type
type MockRepositoriesInterface struct {
	mock.Mock
}

type MockRepositoriesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoriesInterface) EXPECT() *MockRepositoriesInterface_Expecter {
	return &MockRepositoriesInterface_Expecter{mock: &_m.Mock}
}

// DownloadContents provides a mock function with given fields: ctx, owner, repo, filepath, opts
func (_m *MockRepositoriesInterface) DownloadContents(ctx context.Context, owner string, repo string, filepath string, opts *github.RepositoryContentGetOptions) (io.ReadCloser, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, filepath, opts)

	if len(ret) == 0 {
		panic("no return value specified for DownloadContents")
	}

	var r0 io.ReadCloser
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) (io.ReadCloser, *github.Response, error)); ok {
		return rf(ctx, owner, repo, filepath, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) io.ReadCloser); ok {
		r0 = rf(ctx, owner, repo, filepath, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) *github.Response); ok {
		r1 = rf(ctx, owner, repo, filepath, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, *github.RepositoryContentGetOptions) error); ok {
		r2 = rf(ctx, owner, repo, filepath, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepositoriesInterface_DownloadContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadContents'
type MockRepositoriesInterface_DownloadContents_Call struct {
	*mock.Call
}

// DownloadContents is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - filepath string
//   - opts *github.RepositoryContentGetOptions
func (_e *MockRepositoriesInterface_Expecter) DownloadContents(ctx interface{}, owner interface{}, repo interface{}, filepath interface{}, opts interface{}) *MockRepositoriesInterface_DownloadContents_Call {
	return &MockRepositoriesInterface_DownloadContents_Call{Call: _e.mock.On("DownloadContents", ctx, owner, repo, filepath, opts)}
}

func (_c *MockRepositoriesInterface_DownloadContents_Call) Run(run func(ctx context.Context, owner string, repo string, filepath string, opts *github.RepositoryContentGetOptions)) *MockRepositoriesInterface_DownloadContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*github.RepositoryContentGetOptions))
	})
	return _c
}

func (_c *MockRepositoriesInterface_DownloadContents_Call) Return(_a0 io.ReadCloser, _a1 *github.Response, _a2 error) *MockRepositoriesInterface_DownloadContents_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepositoriesInterface_DownloadContents_Call) RunAndReturn(run func(context.Context, string, string, string, *github.RepositoryContentGetOptions) (io.ReadCloser, *github.Response, error)) *MockRepositoriesInterface_DownloadContents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoriesInterface creates a new instance of MockRepositoriesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoriesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoriesInterface {
	mock := &MockRepositoriesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
